Hw1
Fics3/Tink_Java_Backend_Course pull request #1
Opened 2023-10-07 18:05 UTC by Fics3

hw1 done

2023-10-10 20:13 UTC, Stasik371 requested changes

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +    private final static Logger LOGGER = LogManager.getLogger();
Есть очень душная спецификация, что правильно писать 
```suggestion
    private static final Logger LOGGER = LogManager.getLogger();
```

Нужно будет везде исправить

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +                int min = Integer.parseInt(tmp[0]);
min это минимум или минуты? Не очень понятно)

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +                res = (int) Math.log10(Math.abs(value)) + 1;
Красавчик)

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +        return res;
В 12 или 13 JDK появился switch-expression, можно написать return switch(...)

https://www.baeldung.com/java-switch

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +                res = MAX_INT_DIGIT_COUNT;
Немного не понял, почему это выносишь отдельный кейсом?

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task4.java
> +public final class Task4 {
Почему где-то у тебя `final class`, а где-то `public final class`?

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +    public static int findMin(int[] mas) {
Лучше сделать их private) Этот класс должен отдавать наружу только метод с проверкой вложенности массива, а никак не поиска минимума и максимума) Такое нужно сделать везде

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task6.java
> +    private static int count = 0;
Лучше не завязываться на общее поле класса, могут возникнуть проблемы с многопоточностью, о них узнаешь чуть попозже) Предлагаю передавать этот счетчик в рекурсию

2023-10-10 20:13 UTC, Stasik371 commented on src/main/java/edu/hw1/Task8.java
> +    private static final int[][] POSSIBLE_MOVES = {
Красиво)

2023-10-10 20:13 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +        assertEquals(3, countDigits(228));
Нужно приучиться писать тесты по методологии ААА, прочитать можно [здесь](https://habr.com/ru/articles/507594/)

Что хотелось бы видеть:
1. Один метод = один ТестКейс = один случай
2. Понятные названия методов из которых можно понять что происходит в тесте, например countDigits_shouldCountDigitsInNumberIfDataIsValid (Мы в отделе делаем так, можно по-своему, но опять же, нужно передать суть)
3. Хочется комментариев с  `Arrange Act Assert`
4. Неплохо было бы внедрить @DisplayName()
5. Скорее всего для данного случая тебе подойдут параметризированные тесты: вот [тут](https://www.baeldung.com/parameterized-tests-junit-5) есть хорошая статейка)
6. Использовать [assertJ](https://www.baeldung.com/introduction-to-assertj), это вроде даже в условиях сказано)

2023-10-10 20:13 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +        assertEquals(3, countDigits(228));
Чуть ниже приведу пример правильного теста

2023-10-10 20:13 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +    }
```suggestion
    @Test
    @DisplayName(Подсчет цифр числа 0)
    void countDigit_shouldCountDigitOfZero() {
        //arrange
        int zeroNum = 0;
        
        //act
        int actual = Task2.countDigits(zeroNum); 
        
        //assert
        assertThat(actual).isEqualTo(1);
    }
```

2023-10-10 20:13 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +        assertTrue(isPalindromeDescendant(11211230));
Хочется какой-то проверки себя, что это число является палиндромом) В данном случае предлагаю оставить коммент, где ты его раскладываешь). Такое нужно везде

2023-10-10 20:13 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +        assertEquals(73892, minutesToSeconds("1231:32"));
Возможно стоит написать 1231*60+32) Так как-будто понятно, что ты это точно проверил)

2023-10-10 20:13 UTC, Stasik371 commented on src/test/java/edu/hw1/Task6Test.java
> +    }
Еще бы проверить число с 4 одинаковыми цифрами)

2023-10-10 20:13 UTC, Stasik371 commented on src/test/java/edu/hw1/Task7Test.java
> +    public void fullCircleRotateTest() {
Лайк за этот кейс)

2023-10-10 21:05 UTC, Fics3 commented on src/main/java/edu/hw1/Task2.java
> +                res = MAX_INT_DIGIT_COUNT;
потому что MIN_INTEGER -147 483 648, а MAX_INTEGER 2 147 483 647, и если мы будем делать log от него, то все поломается, так как abs значение -147 483 648 выше предела макс инта

2023-10-10 21:06 UTC, Fics3 commented on src/main/java/edu/hw1/Task0.java
> +    private final static Logger LOGGER = LogManager.getLogger();
я это взял из примеров с репозитория, но хорошо, запомню!

2023-10-10 22:15 UTC, Fics3 commented on src/main/java/edu/hw1/Task4.java
> +public final class Task4 {
банальная невнимательность, классы изначально же паблик создаются вроде, поэтому там так и получилось, забыл убрать

2023-10-10 22:33 UTC, Fics3 commented on src/test/java/edu/hw1/Task2Test.java
> +    }
на летней практике мне говорили, что в названии тестов должно присутствовать Test, это в итоге необязательно?

2023-10-15 17:28 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +                res = MAX_INT_DIGIT_COUNT;
Конечно такой себе паттерн, но ничего не поделать, так железки устроены) В целом ок

2023-10-15 17:29 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +    }
В методе теста совсем нет, но вот в классе да, обязательно. Еще следует писать тот же пакет, что и класс, который тестируешь)

2023-10-15 17:32 UTC, Stasik371 commented
Аппрув)

2023-10-15 18:46 UTC, merged