Hw3
Fics3/Tink_Java_Backend_Course pull request #4
Opened 2023-10-19 21:49 UTC by Fics3

2023-11-05 22:38 UTC, Keindel requested changes

2023-11-05 22:38 UTC, Keindel commented on src/main/java/edu/hw3/Task1.java
> +            if (Character.isLetter(currentChar)) {
Обрабатывается случай буква/не буква. Как будет обработана буква не латинского алфавита?

2023-11-05 22:38 UTC, Keindel commented on src/main/java/edu/hw3/Task3.java
> +                frequencyMap.put(item, 1);
предлагаю метод getOrDefault

2023-11-05 22:38 UTC, Keindel commented on src/main/java/edu/hw3/Task5/Contact.java
> +        if (lastFirstNames.length > 1) {
Логику лучше вынести из конструктора в отдельный метод.

2023-11-05 22:38 UTC, Keindel commented on src/main/java/edu/hw3/Task5/Contact.java
> +            lastName = lastFirstNames[0];
Очень странно, что у контакта будет фамилия совпадающая с именем вместо отсутствующей фамилии.))

2023-11-05 22:38 UTC, Keindel commented on src/main/java/edu/hw3/Task5/ParseContacts.java
> +    private static final String ASK = "ASC";
опечатка

2023-11-05 22:38 UTC, Keindel commented on src/main/java/edu/hw3/Task5/ParseContacts.java
> +    public static List<Contact> parseContacts(List<String> contacts, String sortOrder) {
В данном методе происходит сразу несколько разных задач.
Лучше декомпозировать на части. Например: parseContacts(), sortContacts().

2023-11-05 22:38 UTC, Keindel commented on src/main/java/edu/hw3/Task6/Stock.java
> +public class Stock implements Comparable<Stock> {
Сравнение акций по цене не является единственным возможным способом сравнения для сортировки.
Применение Comparator позволило бы на каждый случай реализовать нужную логику сравнения не меняя код в самой акции.

2023-11-06 14:04 UTC, Fics3 commented on src/main/java/edu/hw3/Task3.java
> +                frequencyMap.put(item, 1);
добавление этого метода нужно больше для читаемости или он помогает расширяеть код в будущем?

2023-11-06 15:11 UTC, Fics3 commented on src/main/java/edu/hw3/Task6/Stock.java
> +public class Stock implements Comparable<Stock> {
Когда тогда лучше использовать Comparable, если у нас всего один параметр сравнения?

2023-11-06 20:16 UTC, Keindel commented on src/main/java/edu/hw3/Task3.java
> +                frequencyMap.put(item, 1);
для читаемости

2023-11-06 20:32 UTC, Keindel commented on src/main/java/edu/hw3/Task6/Stock.java
> +public class Stock implements Comparable<Stock> {
Вот несколько статей на тему (но не обязательно читать все):
https://www.digitalocean.com/community/tutorials/comparable-and-comparator-in-java-example
https://www.geeksforgeeks.org/comparable-vs-comparator-in-java/
https://www.baeldung.com/java-comparator-comparable
https://kasunprageethdissanayake.medium.com/comparable-vs-comparator-in-java-623b7435e06
Если очень коротко и просто: Comparable, когда хотите определить естественный порядок для объектов. Comparator, когда нужно указать несколько способов сравнения объектов или когда вы не можете изменить класс, объекты которого вы хотите сравнить.

2023-11-06 21:04 UTC, Keindel requested changes

2023-11-06 21:04 UTC, Keindel commented on src/main/java/edu/hw3/Task1.java
> +            if (Character.isLetter(currentChar) && isLatinLetter(currentChar)) {
латинские буквы - подмножество всех букв, кажется первое условие теперь не нужно

2023-11-06 21:04 UTC, Keindel commented on src/main/java/edu/hw3/Task3.java
> +    private static void getOrDefault(Map<Object, Integer> frequencyMap, Object item) {
Видимо мой комментарий немного ввел в заблуждение. Имелся в виду стандартный библиотечный метод интерфейса Map=)
 https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Map.html#getOrDefault(java.lang.Object,V)

2023-11-06 21:04 UTC, Keindel commented on src/main/java/edu/hw3/Task5/Contact.java
> +    private void splitFullName() {
Можно еще улучшить - вынести логику обработки имен из класса Contact.
Также можно было бы убрать поле fullName, тк оно дублирует информацию других полей.

2023-11-06 21:04 UTC, Keindel commented on src/main/java/edu/hw3/Task5/ParseContacts.java
> +            parsedContacts.sort(Comparator.comparing(Contact::getLastName).reversed()
возможно стоит для имен тоже сделать reversed?

2023-11-06 21:04 UTC, Keindel commented on src/main/java/edu/hw3/Task6/Stock.java
> +public record Stock(String name, int price) {
Цена акций на бирже волатильна, record я бы не рекомендовал.

2023-11-06 21:21 UTC, Fics3 commented on src/main/java/edu/hw3/Task6/Stock.java
> +public class Stock implements Comparable<Stock> {
спасибо большое, стало намного понятнее

2023-11-06 21:22 UTC, Fics3 commented on src/main/java/edu/hw3/Task3.java
> +    private static void getOrDefault(Map<Object, Integer> frequencyMap, Object item) {
Да, не знал об этом методе, хотя давненько с мапами знаком

2023-11-11 11:34 UTC, Keindel requested changes

2023-11-11 11:34 UTC, Keindel commented on src/main/java/edu/hw3/Task6/Stock.java
> +    private final int price;
Цена волатильна, а тут стоит final, этим и было плохо применение record=)

2023-11-11 11:37 UTC, Fics3 commented on src/main/java/edu/hw3/Task6/Stock.java
> +    private final int price;
ааа, простите, идея автоматически предложила и я согласился, совсем не задумался почему то, ну, впередь буду внимательнее

2023-11-11 22:01 UTC, Keindel approved these changes

2023-11-11 22:36 UTC, merged